# Configuration par défaut pour MinePlugin

# Paramètres du mineur
mineur:
  allowed-worlds: [world]
  stop-at-y: -58
  allow-block-placement: false  # true = autoriser piliers, escaliers et torches automatiques
  default:
    pattern: QUARRY
    speed: FAST
    torch-layers: 4
    supports-every: 8
    use-barrel-master: false
  limits:
    max-sessions-per-player: 1
  economy:
    enable: false
    cost-per-layer: 0

# Paramètres de l'éleveur
# Limite d'animaux par espèce dans un enclos
# Temps de restock du PNJ en ticks
# Chance en pourcent d'obtenir de la viande cuite
# Prix en émeraudes pour 64 viandes

eleveur:
  animal-limit: 5
  villager-restock-ticks: 6000   # 5 mn
  loot-cooked-chance: 5          # %
  species: [CHICKEN, COW, PIG, SHEEP, RABBIT]
  emerald-price:
    raw-stack: 1   # 64 viandes crues  => 1 émeraude
    cook-stack: 2  # 64 viandes cuites => 2 émeraudes

# Paramètres du village
village:
  houseSmall: 9
  houseBig: 11
  roadHalf: 2
  spacing: 20
  plazaSize: 9
  rows: 4
  cols: 5
  wallGap: 6        # marge entre les maisons et la muraille
