# Configuration par défaut pour MinePlugin

# Paramètres du mineur
mineur:
  allowed-worlds: [world]
  stop-at-y: -58
  allow-block-placement: false  # true = autoriser piliers, escaliers et torches automatiques
  default:
    pattern: QUARRY
    speed: FAST
    torch-layers: 4
    supports-every: 8
    use-barrel-master: false
  branch:
    spacing: 6        # espacement entre deux branches sur l'axe X
    gallery-width: 3  # largeur de la galerie principale (en blocs)
  limits:
    max-sessions-per-player: 1
  economy:
    enable: false
    cost-per-layer: 0

# Paramètres de l'éleveur
# Limite d'animaux par espèce dans un enclos
# Temps de restock du PNJ en ticks
# Chance en pourcent d'obtenir de la viande cuite
# Prix en émeraudes pour 64 viandes

eleveur:
  animal-limit: 5
  villager-restock-ticks: 6000   # 5 mn
  loot-cooked-chance: 5          # %
  species: [CHICKEN, COW, PIG, SHEEP, RABBIT]
  emerald-price:
    raw-stack: 1   # 64 viandes crues  => 1 émeraude
    cook-stack: 2  # 64 viandes cuites => 2 émeraudes

# Paramètres du village
village:
  houseSmall: 9
  houseBig: 11
  roadHalf: 2
  spacing: 20
  plazaSize: 9
  rows: 4
  cols: 5
  wallGap: 6        # marge entre les maisons et la muraille

# Paramètres des métiers
jobs:
  mineur:
    xp-per-block:
      STONE: 1
      COBBLESTONE: 1
      DEEPSLATE: 1

      COAL_ORE: 3
      DEEPSLATE_COAL_ORE: 3

      COPPER_ORE: 4
      DEEPSLATE_COPPER_ORE: 4

      IRON_ORE: 5
      DEEPSLATE_IRON_ORE: 5

      GOLD_ORE: 6
      DEEPSLATE_GOLD_ORE: 6

      REDSTONE_ORE: 6
      DEEPSLATE_REDSTONE_ORE: 6

      LAPIS_ORE: 7
      DEEPSLATE_LAPIS_ORE: 7

      DIAMOND_ORE: 10
      DEEPSLATE_DIAMOND_ORE: 10

      EMERALD_ORE: 12
      DEEPSLATE_EMERALD_ORE: 12

      NETHER_QUARTZ_ORE: 4
      NETHER_GOLD_ORE: 6
